# global settings
# [global]
# auth_header = 'x-api-key'
# timeout = 900
# trusted_proxies = ["127.0.0.1", "::1"]

[routes.example]
shell = "/usr/bin/bash"
args = [ "examples/loop.sh" ]
keys = "examples/keys"
concurrency = 1
